# Report customization configuration
report_title: 'Some really cool title'
institution:
  name: 'SciLifeLab'
  img: 'assets/img/scilifelab.jpg'
  url: 'https://www.scilifelab.se'
date_format: '%Y-%m-%d'
assets:
  css:
  js:
