name: CI [dev]

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.18
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.18

    - name: Install dependencies & package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        python setup.py install

    - name: Lint
      run: |
        flake8 fusion_report/
        mypy fusion_report/

    - name: Quick test
      run: |
        fusion_report --help
        fusion_report run --help
        fusion_report download --help
