name: Docker Image CI [ master ]

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build only
        id: docker_build_only
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: clinicalgenomics/fusion-report:2.1.5p7
