name: Docker Image CI [mittelman_fix]

on:
  push:
    branches: [ mittelman_fix ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag 2.1.5patched:$(date +%s)



      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build only
        id: docker_build_only
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: false
          tags: clinicalgenomics/fusion-report:2.1.5patched
