name: Integration Tests

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies & package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          python setup.py install

      - name: Test download of databases
        run: fusion_report download --cosmic_usr "${{ secrets.COSMIC_USERNAME }}" --cosmic_passwd "${{ secrets.COSMIC_PASSWD }}" ./db

      - name: Test run
        run: |
          fusion_report run "example-sample" ./docs/example ./db/ \
            --arriba tests/test_data/arriba.tsv \
            --fusioncatcher tests/test_data/fusioncatcher.txt \
            --starfusion tests/test_data/starfusion.tsv \
            --starfusion_lr tests/test_data/starfusion_lr.tsv \
            --export csv
