name: CI [master]

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.18
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.18

    - name: Install dependencies & package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        python setup.py install

    - name: Lint
      run: |
        flake8 fusion_report/
        mypy fusion_report/

    - name: Test
      run: fusion_report download --cosmic_usr "${{ secrets.USERNAME }}" --cosmic_passwd "${{ secrets.PASSWORD }}" ./db

    - name: Run application
      run: |
        fusion_report run "example-sample" ./docs/example ./db/ \
          --arriba tests/test_data/arriba.tsv \
          --dragen tests/test_data/dragen.tsv \
          --ericscript tests/test_data/ericscript.tsv \
          --fusioncatcher tests/test_data/fusioncatcher.txt \
          --pizzly tests/test_data/pizzly.tsv \
          --squid tests/test_data/squid.txt \
          --starfusion tests/test_data/starfusion.tsv \
          --export csv

    - name: Build example
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add docs/example
        git commit -m "docs: generate example ($(echo ${GITHUB_SHA} | cut -c1-7))"
        git push origin master

    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
